# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila.xci
# IP: The module: 'ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila.xci
# IP: The module: 'ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
