set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel_seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports op]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN W4 [get_ports {sel_seg[3]}]
set_property PACKAGE_PIN V4 [get_ports {sel_seg[2]}]
set_property PACKAGE_PIN U4 [get_ports {sel_seg[1]}]
set_property PACKAGE_PIN U2 [get_ports {sel_seg[0]}]
set_property PACKAGE_PIN W7 [get_ports {seg[6]}]
set_property PACKAGE_PIN W6 [get_ports {seg[5]}]
set_property PACKAGE_PIN U8 [get_ports {seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[2]}]
set_property PACKAGE_PIN V5 [get_ports {seg[1]}]
set_property PACKAGE_PIN U7 [get_ports {seg[0]}]
set_property PACKAGE_PIN T18 [get_ports rst]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports add]
set_property IOSTANDARD LVCMOS33 [get_ports minus]
set_property PACKAGE_PIN T17 [get_ports add]
set_property PACKAGE_PIN W19 [get_ports minus]
set_property PACKAGE_PIN U18 [get_ports op]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} [get_ports clk]