# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/ila/ila.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila} -quiet] -quiet

# IP: ip/clk_wiz_1/clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet
