# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/OTHERS/vivado_study/exp/exp.srcs/sources_1/ip/test_ROM_distributed/test_ROM_distributed.xci
# IP: The module: 'test_ROM_distributed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/OTHERS/vivado_study/exp/exp.srcs/sources_1/ip/test_ROM_distributed/test_ROM_distributed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_ROM_distributed'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/OTHERS/vivado_study/exp/exp.srcs/sources_1/ip/test_ROM_distributed/test_ROM_distributed.xci
# IP: The module: 'test_ROM_distributed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/OTHERS/vivado_study/exp/exp.srcs/sources_1/ip/test_ROM_distributed/test_ROM_distributed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_ROM_distributed'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
