# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# IP: ip/sys_clk/sys_clk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_clk || ORIG_REF_NAME==sys_clk} -quiet] -quiet
