# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/verify_RAM/verify_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==verify_RAM || ORIG_REF_NAME==verify_RAM} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
