# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/OTHERS/vivado_study/pipeline/exp.cache/wt [current_project]
set_property parent.project_path C:/OTHERS/vivado_study/pipeline/exp.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/OTHERS/vivado_study/pipeline/exp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/OTHERS/vivado_study/pipeline/sort_input.coe
add_files C:/OTHERS/vivado_study/pipeline/sort_output.coe
add_files c:/OTHERS/vivado_study/pipeline/sort_output_final_4.coe
add_files c:/OTHERS/vivado_study/pipeline/sort_input_final_4.coe
read_verilog -library xil_defaultlib {
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/conditional.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/adder.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/if_zero.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/alu.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/regfile.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/ROM.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/controller.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/top.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/mux2.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/datapath.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/extend.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/imem.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/eqcmp.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/flopenrc.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/arm.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/dmem.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/main_test_pipeline.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/mux3.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/ROM_out.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/floprc.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/shifter.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/hazard.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/flopr.v
  C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/imports/new/flopenr.v
}
read_ip -quiet C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/verify_RAM/verify_RAM.xci
set_property used_in_implementation false [get_files -all c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/verify_RAM/verify_RAM_ooc.xdc]

read_ip -quiet C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila.xci
set_property used_in_synthesis false [get_files -all c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ila/ila_ooc.xdc]

read_ip -quiet C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/test_ROM_distributed/test_ROM_distributed.xci
set_property used_in_implementation false [get_files -all c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/test_ROM_distributed/test_ROM_distributed_ooc.xdc]

read_ip -quiet C:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ROM_output/ROM_output.xci
set_property used_in_implementation false [get_files -all c:/OTHERS/vivado_study/pipeline/exp.srcs/sources_1/ip/ROM_output/ROM_output_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/OTHERS/vivado_study/pipeline/exp.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/OTHERS/vivado_study/pipeline/exp.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main_test_pipeline -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main_test_pipeline.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_test_pipeline_utilization_synth.rpt -pb main_test_pipeline_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
