set_property PACKAGE_PIN W5 [get_ports clk_osc]
set_property IOSTANDARD LVCMOS33 [get_ports clk_osc]
set_property PACKAGE_PIN R2 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN U16 [get_ports test]
set_property IOSTANDARD LVCMOS33 [get_ports test]